# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calcwindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CalcWindow(object):
    def setupUi(self, CalcWindow):
        CalcWindow.setObjectName("CalcWindow")
        CalcWindow.resize(380, 250)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CalcWindow.sizePolicy().hasHeightForWidth())
        CalcWindow.setSizePolicy(sizePolicy)
        CalcWindow.setMinimumSize(QtCore.QSize(380, 250))
        self.centralWidget = QtWidgets.QWidget(CalcWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.line_edit = QtWidgets.QLineEdit(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_edit.sizePolicy().hasHeightForWidth())
        self.line_edit.setSizePolicy(sizePolicy)
        self.line_edit.setMinimumSize(QtCore.QSize(0, 40))
        self.line_edit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.line_edit.setObjectName("line_edit")
        self.gridLayout_2.addWidget(self.line_edit, 0, 0, 1, 1)
        self.main_layout = QtWidgets.QGridLayout()
        self.main_layout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.main_layout.setContentsMargins(11, 11, 11, 11)
        self.main_layout.setSpacing(6)
        self.main_layout.setObjectName("main_layout")
        self.btn_plus = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_plus.sizePolicy().hasHeightForWidth())
        self.btn_plus.setSizePolicy(sizePolicy)
        self.btn_plus.setMinimumSize(QtCore.QSize(50, 30))
        self.btn_plus.setObjectName("btn_plus")
        self.main_layout.addWidget(self.btn_plus, 2, 6, 1, 1)
        self.btn_num8 = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_num8.sizePolicy().hasHeightForWidth())
        self.btn_num8.setSizePolicy(sizePolicy)
        self.btn_num8.setMinimumSize(QtCore.QSize(50, 30))
        self.btn_num8.setObjectName("btn_num8")
        self.main_layout.addWidget(self.btn_num8, 2, 4, 1, 1)
        self.btn_num7 = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_num7.sizePolicy().hasHeightForWidth())
        self.btn_num7.setSizePolicy(sizePolicy)
        self.btn_num7.setMinimumSize(QtCore.QSize(50, 30))
        self.btn_num7.setObjectName("btn_num7")
        self.main_layout.addWidget(self.btn_num7, 2, 3, 1, 1)
        self.btn_num9 = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_num9.sizePolicy().hasHeightForWidth())
        self.btn_num9.setSizePolicy(sizePolicy)
        self.btn_num9.setMinimumSize(QtCore.QSize(50, 30))
        self.btn_num9.setObjectName("btn_num9")
        self.main_layout.addWidget(self.btn_num9, 2, 5, 1, 1)
        self.btn_minus = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_minus.sizePolicy().hasHeightForWidth())
        self.btn_minus.setSizePolicy(sizePolicy)
        self.btn_minus.setMinimumSize(QtCore.QSize(50, 30))
        self.btn_minus.setObjectName("btn_minus")
        self.main_layout.addWidget(self.btn_minus, 3, 6, 1, 1)
        self.btn_num4 = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_num4.sizePolicy().hasHeightForWidth())
        self.btn_num4.setSizePolicy(sizePolicy)
        self.btn_num4.setMinimumSize(QtCore.QSize(50, 30))
        self.btn_num4.setObjectName("btn_num4")
        self.main_layout.addWidget(self.btn_num4, 3, 3, 1, 1)
        self.btn_num6 = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_num6.sizePolicy().hasHeightForWidth())
        self.btn_num6.setSizePolicy(sizePolicy)
        self.btn_num6.setMinimumSize(QtCore.QSize(50, 30))
        self.btn_num6.setObjectName("btn_num6")
        self.main_layout.addWidget(self.btn_num6, 3, 5, 1, 1)
        self.btn_num5 = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_num5.sizePolicy().hasHeightForWidth())
        self.btn_num5.setSizePolicy(sizePolicy)
        self.btn_num5.setMinimumSize(QtCore.QSize(50, 30))
        self.btn_num5.setObjectName("btn_num5")
        self.main_layout.addWidget(self.btn_num5, 3, 4, 1, 1)
        self.btn_factorial = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_factorial.sizePolicy().hasHeightForWidth())
        self.btn_factorial.setSizePolicy(sizePolicy)
        self.btn_factorial.setMinimumSize(QtCore.QSize(50, 30))
        self.btn_factorial.setObjectName("btn_factorial")
        self.main_layout.addWidget(self.btn_factorial, 4, 1, 1, 1)
        self.btn_num1 = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_num1.sizePolicy().hasHeightForWidth())
        self.btn_num1.setSizePolicy(sizePolicy)
        self.btn_num1.setMinimumSize(QtCore.QSize(50, 30))
        self.btn_num1.setObjectName("btn_num1")
        self.main_layout.addWidget(self.btn_num1, 4, 3, 1, 1)
        self.btn_num2 = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_num2.sizePolicy().hasHeightForWidth())
        self.btn_num2.setSizePolicy(sizePolicy)
        self.btn_num2.setMinimumSize(QtCore.QSize(50, 30))
        self.btn_num2.setObjectName("btn_num2")
        self.main_layout.addWidget(self.btn_num2, 4, 4, 1, 1)
        self.btn_mod = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_mod.sizePolicy().hasHeightForWidth())
        self.btn_mod.setSizePolicy(sizePolicy)
        self.btn_mod.setMinimumSize(QtCore.QSize(50, 30))
        self.btn_mod.setObjectName("btn_mod")
        self.main_layout.addWidget(self.btn_mod, 5, 1, 1, 1)
        self.btn_num0 = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_num0.sizePolicy().hasHeightForWidth())
        self.btn_num0.setSizePolicy(sizePolicy)
        self.btn_num0.setMinimumSize(QtCore.QSize(50, 30))
        self.btn_num0.setObjectName("btn_num0")
        self.main_layout.addWidget(self.btn_num0, 5, 3, 1, 1)
        self.btn_num3 = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_num3.sizePolicy().hasHeightForWidth())
        self.btn_num3.setSizePolicy(sizePolicy)
        self.btn_num3.setMinimumSize(QtCore.QSize(50, 30))
        self.btn_num3.setObjectName("btn_num3")
        self.main_layout.addWidget(self.btn_num3, 4, 5, 1, 1)
        self.btn_multiply = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_multiply.sizePolicy().hasHeightForWidth())
        self.btn_multiply.setSizePolicy(sizePolicy)
        self.btn_multiply.setMinimumSize(QtCore.QSize(50, 30))
        self.btn_multiply.setObjectName("btn_multiply")
        self.main_layout.addWidget(self.btn_multiply, 4, 6, 1, 1)
        self.btn_dot = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_dot.sizePolicy().hasHeightForWidth())
        self.btn_dot.setSizePolicy(sizePolicy)
        self.btn_dot.setMinimumSize(QtCore.QSize(50, 30))
        self.btn_dot.setObjectName("btn_dot")
        self.main_layout.addWidget(self.btn_dot, 5, 4, 1, 1)
        self.btn_equal = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_equal.sizePolicy().hasHeightForWidth())
        self.btn_equal.setSizePolicy(sizePolicy)
        self.btn_equal.setMinimumSize(QtCore.QSize(50, 30))
        self.btn_equal.setObjectName("btn_equal")
        self.main_layout.addWidget(self.btn_equal, 5, 5, 1, 1)
        self.btn_divide = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_divide.sizePolicy().hasHeightForWidth())
        self.btn_divide.setSizePolicy(sizePolicy)
        self.btn_divide.setMinimumSize(QtCore.QSize(50, 30))
        self.btn_divide.setObjectName("btn_divide")
        self.main_layout.addWidget(self.btn_divide, 5, 6, 1, 1)
        self.btn_neg = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_neg.sizePolicy().hasHeightForWidth())
        self.btn_neg.setSizePolicy(sizePolicy)
        self.btn_neg.setMinimumSize(QtCore.QSize(50, 30))
        self.btn_neg.setObjectName("btn_neg")
        self.main_layout.addWidget(self.btn_neg, 5, 0, 1, 1)
        self.btn_pow2 = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_pow2.sizePolicy().hasHeightForWidth())
        self.btn_pow2.setSizePolicy(sizePolicy)
        self.btn_pow2.setMinimumSize(QtCore.QSize(50, 30))
        self.btn_pow2.setObjectName("btn_pow2")
        self.main_layout.addWidget(self.btn_pow2, 4, 0, 1, 1)
        self.btn_powa = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_powa.sizePolicy().hasHeightForWidth())
        self.btn_powa.setSizePolicy(sizePolicy)
        self.btn_powa.setMinimumSize(QtCore.QSize(50, 30))
        self.btn_powa.setObjectName("btn_powa")
        self.main_layout.addWidget(self.btn_powa, 3, 0, 1, 1)
        self.btn_sqrt = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_sqrt.sizePolicy().hasHeightForWidth())
        self.btn_sqrt.setSizePolicy(sizePolicy)
        self.btn_sqrt.setMinimumSize(QtCore.QSize(50, 30))
        self.btn_sqrt.setObjectName("btn_sqrt")
        self.main_layout.addWidget(self.btn_sqrt, 3, 1, 1, 1)
        self.btn_c = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_c.sizePolicy().hasHeightForWidth())
        self.btn_c.setSizePolicy(sizePolicy)
        self.btn_c.setMinimumSize(QtCore.QSize(50, 30))
        self.btn_c.setObjectName("btn_c")
        self.main_layout.addWidget(self.btn_c, 2, 0, 1, 1)
        self.btn_ce = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_ce.sizePolicy().hasHeightForWidth())
        self.btn_ce.setSizePolicy(sizePolicy)
        self.btn_ce.setMinimumSize(QtCore.QSize(50, 30))
        self.btn_ce.setObjectName("btn_ce")
        self.main_layout.addWidget(self.btn_ce, 2, 1, 1, 1)
        self.gridLayout_2.addLayout(self.main_layout, 1, 0, 1, 1)
        CalcWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(CalcWindow)
        QtCore.QMetaObject.connectSlotsByName(CalcWindow)
        CalcWindow.setTabOrder(self.line_edit, self.btn_num0)
        CalcWindow.setTabOrder(self.btn_num0, self.btn_num1)
        CalcWindow.setTabOrder(self.btn_num1, self.btn_num2)
        CalcWindow.setTabOrder(self.btn_num2, self.btn_num3)
        CalcWindow.setTabOrder(self.btn_num3, self.btn_num4)
        CalcWindow.setTabOrder(self.btn_num4, self.btn_num5)
        CalcWindow.setTabOrder(self.btn_num5, self.btn_num6)
        CalcWindow.setTabOrder(self.btn_num6, self.btn_num7)
        CalcWindow.setTabOrder(self.btn_num7, self.btn_num8)
        CalcWindow.setTabOrder(self.btn_num8, self.btn_num9)
        CalcWindow.setTabOrder(self.btn_num9, self.btn_dot)
        CalcWindow.setTabOrder(self.btn_dot, self.btn_equal)
        CalcWindow.setTabOrder(self.btn_equal, self.btn_plus)
        CalcWindow.setTabOrder(self.btn_plus, self.btn_minus)
        CalcWindow.setTabOrder(self.btn_minus, self.btn_multiply)
        CalcWindow.setTabOrder(self.btn_multiply, self.btn_divide)
        CalcWindow.setTabOrder(self.btn_divide, self.btn_neg)
        CalcWindow.setTabOrder(self.btn_neg, self.btn_pow2)
        CalcWindow.setTabOrder(self.btn_pow2, self.btn_factorial)
        CalcWindow.setTabOrder(self.btn_factorial, self.btn_mod)

    def retranslateUi(self, CalcWindow):
        _translate = QtCore.QCoreApplication.translate
        CalcWindow.setWindowTitle(_translate("CalcWindow", "CalcWindow"))
        self.btn_plus.setText(_translate("CalcWindow", "+"))
        self.btn_plus.setShortcut(_translate("CalcWindow", "+"))
        self.btn_num8.setText(_translate("CalcWindow", "8"))
        self.btn_num8.setShortcut(_translate("CalcWindow", "8"))
        self.btn_num7.setText(_translate("CalcWindow", "7"))
        self.btn_num7.setShortcut(_translate("CalcWindow", "7"))
        self.btn_num9.setText(_translate("CalcWindow", "9"))
        self.btn_num9.setShortcut(_translate("CalcWindow", "9"))
        self.btn_minus.setText(_translate("CalcWindow", "-"))
        self.btn_minus.setShortcut(_translate("CalcWindow", "-"))
        self.btn_num4.setText(_translate("CalcWindow", "4"))
        self.btn_num4.setShortcut(_translate("CalcWindow", "4"))
        self.btn_num6.setText(_translate("CalcWindow", "6"))
        self.btn_num6.setShortcut(_translate("CalcWindow", "6"))
        self.btn_num5.setText(_translate("CalcWindow", "5"))
        self.btn_num5.setShortcut(_translate("CalcWindow", "5"))
        self.btn_factorial.setText(_translate("CalcWindow", "n!"))
        self.btn_factorial.setShortcut(_translate("CalcWindow", "!"))
        self.btn_num1.setText(_translate("CalcWindow", "1"))
        self.btn_num1.setShortcut(_translate("CalcWindow", "1"))
        self.btn_num2.setText(_translate("CalcWindow", "2"))
        self.btn_num2.setShortcut(_translate("CalcWindow", "2"))
        self.btn_mod.setText(_translate("CalcWindow", "Mod"))
        self.btn_mod.setShortcut(_translate("CalcWindow", "%"))
        self.btn_num0.setText(_translate("CalcWindow", "0"))
        self.btn_num0.setShortcut(_translate("CalcWindow", "0"))
        self.btn_num3.setText(_translate("CalcWindow", "3"))
        self.btn_num3.setShortcut(_translate("CalcWindow", "3"))
        self.btn_multiply.setText(_translate("CalcWindow", "*"))
        self.btn_multiply.setShortcut(_translate("CalcWindow", "*"))
        self.btn_dot.setText(_translate("CalcWindow", "."))
        self.btn_dot.setShortcut(_translate("CalcWindow", "."))
        self.btn_equal.setText(_translate("CalcWindow", "="))
        self.btn_equal.setShortcut(_translate("CalcWindow", "Return"))
        self.btn_divide.setText(_translate("CalcWindow", "/"))
        self.btn_divide.setShortcut(_translate("CalcWindow", "/"))
        self.btn_neg.setText(_translate("CalcWindow", "-n"))
        self.btn_neg.setShortcut(_translate("CalcWindow", "$"))
        self.btn_pow2.setText(_translate("CalcWindow", "n^2"))
        self.btn_pow2.setShortcut(_translate("CalcWindow", "&"))
        self.btn_powa.setText(_translate("CalcWindow", "n^a"))
        self.btn_powa.setShortcut(_translate("CalcWindow", "^"))
        self.btn_sqrt.setText(_translate("CalcWindow", "Sqrt(n)"))
        self.btn_sqrt.setShortcut(_translate("CalcWindow", "N"))
        self.btn_c.setText(_translate("CalcWindow", "C"))
        self.btn_c.setShortcut(_translate("CalcWindow", "Esc"))
        self.btn_ce.setText(_translate("CalcWindow", "CE"))
        self.btn_ce.setShortcut(_translate("CalcWindow", "Backspace"))

