# Uncomment lines below if you have problems with $PATH
#SHELL := /bin/bash
#PATH := /usr/local/bin:$(PATH)

all:
	sudo platformio -f -c vim run

upload:
	sudo platformio -f -c vim run --target upload

clean:
	sudo platformio -f -c vim run --target clean

program:
	sudo platformio -f -c vim run --target program

uploadfs:
	sudo platformio -f -c vim run --target uploadfs

update:
	sudo platformio -f -c vim update

monitor:
	sudo platformio device monitor
