DROP SEQUENCE seq_Prava;
DROP TABLE Mistnost CASCADE CONSTRAINTS;
DROP TABLE Ucebna CASCADE CONSTRAINTS;
DROP TABLE Kancelar CASCADE CONSTRAINTS;
DROP TABLE Porucha CASCADE CONSTRAINTS;
DROP TABLE Presun CASCADE CONSTRAINTS;
DROP TABLE Prava CASCADE CONSTRAINTS;
DROP TABLE Zarizeni CASCADE CONSTRAINTS;
DROP TABLE Oddeleni CASCADE CONSTRAINTS;
DROP TABLE Zamestnanec CASCADE CONSTRAINTS;

